### PR TITLE
Add webapp menu service documentation

### PR DESCRIPTION
**Pull request by phfarolfi**
Considering the lacking of information about the menu service, I'm responsible to create a documentation to make its use more clear.

### CODE REVIEW

**Comment by AnnyCaroline** [comment]
@phfarolfi, I miss some examples and how to import the service. My suggestion is:

- start the text explaining where the service is available (like https://platform.intelie.com/~/revisions/ifrM4aoBY6AkwKLuY4bi/developers/web-application/dashboard-and-widgets/live-widget-api) and what it is (you already did this last part at "Used to attach a new item ... "Apps", "Console"";
- explain the API methods;
- only then explain the types `MenuItem` and `MenuType`. I suggest including if the parameter is required or not, and its default value. Also, include some explanation about the `RightMenuItem` and its properties `description` and `icon`;
- show some examples. If possible, include some images showing the results;
- remove the `code`. I don't think it's necessary for who will use the service.

**Comment by AnnyCaroline** [comment]
@phfarolfi , could you please:

- add an example using the `selectedAliases`?
- use headers for each example? This would help readers to copy and paste examples. I propose to change an example from this:

````markdown
> Console menu output:
![Console menu output](../../../.gitbook/assets/menu-service-example4.gif)

> Apps menu example:

```typescript
const Test = (): JSX.Element => <h1 style={{ padding: '50px 20px'}}>Test</h1>

Router.route('app/test', Test, 'test')

MenuService.register(
    {
        alias: 'test',
        name: 'Test Menu',
        url: '/#/app/test',
        config: {
            description: 'Test description for apps'
        }
    },
    'regular'
)
```
````

To this:
````markdown
## Apps menu example:

``` typescript
const Test = (): JSX.Element => <h1 style={{ padding: '50px 20px'}}>Test</h1>

Router.route('app/test', Test, 'test')

MenuService.register(
    {
        alias: 'test',
        name: 'Test Menu',
        url: '/#/app/test',
        config: {
            description: 'Test description for apps'
        }
    },
    'regular'
)
```

![Regular menu output](<../../../.gitbook/assets/menu-service-example1.png>)

````

**Comment by fabiobm** [comment]
The `selectedAliases` example isn't working for me.

If I manually navigate to `/#/test` it works, but if I click on the menu button it changes the URL to `/#/test-url` without actually loading the registered component.

**Comment by fabiobm** [comment]
I think we should add an example using the `replaces` attribute, and also use this to note that the `Home` menu should not be replaced using this, but instead by using the custom home page API (can add a link to the documentation for that)

**Comment by AnnyCaroline** [comment]
@phfarolfi , maybe we could add a documentation about LiveApi.Extension.configuration.entries.registry.

**Comment by phfarolfi** [comment]
> @phfarolfi , maybe we could add a documentation about LiveApi.Extension.configuration.entries.registry.

I think it's a good idea, but should be made in another PR as it's not related to menuService. WDYT?

**Pull request merged**
